name: Espresso CI
# on push we will trigger our code
on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest # the machine type
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level for example [25,23,28]
        target: [default]
        profile: ["Nexus 6", "Nexus 6P", "Nexus 9", "Nexus S", "Nexus 5X", "pixel_2", "pixel_c", "pixel_xl", "pixel_3a", "pixel_4_xl"]
        #profile: ["Nexus 6"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2 #checkout the code

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Giving Gradlew correct permissions
      run: chmod +x gradlew

    - name: Run Espresso Tests
      uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: ${{ matrix.profile }}
        script: bash installApkAndRunTest.sh


    #- name: Send mail
    #  uses: dawidd6/action-send-mail@v3
    #  with:
        # Required mail server address:
    #    server_address: smtp.ethereal.email
        # Required mail server port:
    #    server_port: 587
        # Optional (recommended): mail server username:
    #    username: kyler.pfeffer83@ethereal.email
        # Optional (recommended) mail server password:
    #    password: q26wRdRveXFmUJHP7G
        # Required mail subject:
    #    subject: Github Actions job result
        # Required recipients' addresses:
    #    to: obiwan@example.com,yoda@example.com
        # Required sender full name (address can be skipped):
    #    from: Luke Skywalker # <user@example.com>
        # Optional HTML body read from file:
    #    html_body: file:///Users/runner/work/EspressoContinuousIntegration/EspressoContinuousIntegration/omniNotes/build/outputs/androidTest-results/connected/flavors/playDebugAndroidTest/TEST-test(AVD) - 7.1.1-omniNotes-playDebugAndroidTest.xml

    - uses: actions/upload-artifact@v2
      with:
        name: test-report of ${{ matrix.profile }}
        path: /Users/runner/work/EspressoContinuousIntegration/EspressoContinuousIntegration/omniNotes/build/outputs/androidTest-results/*
