name: Espresso CI
# on push we will trigger our code
on: [push]

jobs:
  build:
    runs-on: macos-latest # the machine type
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level for example [25,23,28]
        target: [default]
    steps:
    - uses: actions/checkout@v2 #checkout the code

    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 16

    - name: Giving Gradlew correct permissions
      run: chmod +x gradlew

    - name: Run Espresso Tests
      uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: bash installApkAndRunTest.sh


    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.ethereal.email
        # Required mail server port:
        server_port: 587
        # Optional (recommended): mail server username:
        username: kyler.pfeffer83@ethereal.email
        # Optional (recommended) mail server password:
        password: q26wRdRveXFmUJHP7G
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: obiwan@example.com,yoda@example.com
        # Required sender full name (address can be skipped):
        from: Luke Skywalker # <user@example.com>
        # Optional HTML body read from file:
        html_body: file:///Users/runner/work/AppiumContinuousIntegration/EspressoContinuousIntegration/result.txt

